version: '3.8'
services:
  builder:
    platform: linux/amd64
    build: .
    volumes:
      - .:/workspace
      - ./build:/workspace/build
      - cargo-cache:/root/.cargo
      - target-cache:/workspace/target

volumes:
  cargo-cache:
  target-cache: