[package]
name = "cb2pgn-jni"
version = "0.1.0"
edition = "2015"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.19.0", features = ["default"] }
uncbv = { path = "../uncbv" }

[dependencies.libc]
version = "0.2.82"  # An older version that doesn't use edition 2021